vim.api.nvim_set_hl(0, "CursorLineNr", { link = "CursorLine" })
vim.api.nvim_set_hl(0, "CursorLineSign", { link = "CursorLine" })
vim.api.nvim_set_hl(0, "CursorLineFold", { link = "CursorLine" })
vim.api.nvim_set_hl(0, "MiniStatuscolumnSep", { link = "LineNr" })
vim.api.nvim_set_hl(0, "MiniStatuscolumnSepCursor", { link = "LineNr" })
