local config = require("config")
return {
  {
    "folke/snacks.nvim",
    enabled = (config.finder == "snacks"),
    priority = 1000,
    lazy = false,
    keys = {
      { "<leader>fl",      function() Snacks.picker.picker_layouts() end,                         desc = "Layout" },
      { "<leader>fo",      function() Snacks.picker.treesitter() end,                             desc = "Treesitter" },
      { "<leader><enter>", function() Snacks.picker.smart() end,                                  desc = "Smart Find Files" },
      { "<leader>,",       function() Snacks.picker.buffers() end,                                desc = "Buffers" },
      { "<leader>/",       function() Snacks.picker.grep({ cwd = require("utils").root() }) end,  desc = "Grep(root)" },
      { "<leader>fb",      function() Snacks.picker.buffers() end,                                desc = "Buffers" },
      { "<leader>ff",      function() Snacks.picker.files({ cwd = require("utils").root() }) end, desc = "Find Files(root)" },
      { "<leader>fF",      function() Snacks.picker.files() end,                                  desc = "Find Files(cwd)" },
      { "<leader>fr",      function() Snacks.picker.recent() end,                                 desc = "Recent" },
      { "<leader>sg",      function() Snacks.picker.grep({ cwd = require("utils").root() }) end,  desc = "Grep(root)" },
      { "<leader>sG",      function() Snacks.picker.grep() end,                                   desc = "Grep(cwd)" },
      { "<leader>sR",      function() Snacks.picker.resume() end,                                 desc = "Resume" },
      { "<leader>sw",      function() Snacks.picker.grep({ cwd = require("utils").root() }) end,  desc = "Visual selection or word(root)", mode = { "n", "x" } },
      { "<leader>sW",      function() Snacks.picker.grep_word() end,                              desc = "Visual selection or word(cwd)",  mode = { "n", "x" } },
      { "gd",              function() Snacks.picker.lsp_definitions() end,                        desc = "Goto Definition" },
      { "gD",              function() Snacks.picker.lsp_declarations() end,                       desc = "Goto Declaration" },
      { "grr",             function() Snacks.picker.lsp_references() end,                         nowait = true,                           desc = "References" },
      { "gri",             function() Snacks.picker.lsp_implementations() end,                    desc = "Goto Implementation" },
      { "grt",             function() Snacks.picker.lsp_type_definitions() end,                   desc = "Goto T[y]pe Definition" },
      { "<leader>ss",      function() Snacks.picker.lsp_symbols() end,                            desc = "LSP Symbols" },
      { "<leader>sS",      function() Snacks.picker.lsp_workspace_symbols() end,                  desc = "LSP Workspace Symbols" },
    },
    opts = {
      bigfile = { enabled = false },
      dashboard = { enabled = false },
      explorer = { enabled = false },
      indent = { enabled = false },
      input = { enabled = true },
      picker = { enabled = true },
      notifier = { enabled = false },
      quickfile = { enabled = true },
      scope = { enabled = true },
      scroll = { enabled = true },
      statuscolumn = { enabled = false },
      words = { enabled = true },
    },
  }
}
